services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./datasets:/datasets:ro
      - ./models:/models
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4g
    restart: unless-stopped