version: "3.9"
services:
  api:
    build: .
    container_name: yolov8-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4g
    restart: unless-stopped


